### ISSUE TITLE
Keyboard dismiss options for 'Add Event' form

### ISSUE THREAD

**Issue by SaurabhJamadagni** [jordibruin/dayssince#6]
Hi @jordibruin @vickipetrova :)

I recently downloaded Days Since. I really enjoy the app. Saw many apps that count down to a particular day but hadn't come across one that counts down from an important memory. Coupled with the UI it's such a fun app. 

Raising this issue as I noticed a tiny tweak that could be made to the `AddItemForm`. It is about dismissing the keyboard. The natural instinct with most apps has become to swipe down to dismiss the keyboard, or pressing the 'Done' key in the toolbar. 

![daysSince](https://user-images.githubusercontent.com/68957712/215275723-67813619-c07a-440f-b2ad-f6ac064b3468.gif)

Although 'Return' does dismiss the keyboard, I felt implementing the swipe gesture and or the done key might be a nice tweak to the experience. As of right now a downward swipe dismisses the form and if done by mistake could make the user have to retype the event.

It's super trivial and I absolutely don't mean to be picky. Let me know if you think it would be a good addition and if I could work on it. I would love to contribute.

**Comment by vickipetrova** [comment]
Hi @SaurabhJamadagni! Thank you for raising the issue. I've actually had problems with implementing a nice way to close the keyboard. Adding a 'Done' button in the keyboard toolbar is a bit ugly so for now I've actually added it to the navigation view toolbar. But I think it would be nice to also dismiss the keyboard when the user taps outside of it. I haven't been able to implement this. Whatever method I've tried it interferes with other tap gestures in the sheet. Would you be interested in working on that approach of dismissing the keyboard and/or the swipe down gesture? :) The only thing for the swipe gesture downwards, I'm considering is that it might be confusing because you swipe down to dismiss the whole sheet hmm... I wonder if it would feel nice to use but we can try 😄

**Comment by SaurabhJamadagni** [comment]
Hey @vickipetrova, I completely agree about the 'Done' button in the toolbar looking ugly. That is why I was thinking about a swipe method. But one more button implementation that came to my mind is we could turn the return button into the blue button that says done. Here's a screenshot of what I mean:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/68957712/221867047-be0dbe78-c536-4c31-b6b7-d8137788c2a1.png">

Do you think this could be one of the possible implementation? 

I would love to work on this issue. No problem at all. Should I try a swipe implementation or tap implementation first?

**Comment by vickipetrova** [comment]
Whatever you have inspiration for 😄

**Comment by SaurabhJamadagni** [comment]
> Whatever you have inspiration for 😄

Awesome! Thanks @vickipetrova. What do you think about the done button implementation in the keyboard as in the screenshot above though? Should I keep that too?

**Comment by vickipetrova** [comment]
Thank you so much @SaurabhJamadagni  for the great solution! 😊
